version: '3.8'

services:
  mysqldatabase:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: netguru
    ports:
      - $MYSQL_EXTERNAL_PORT:3306
    volumes:
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: netguru-task
    volumes:
      - .:/app/
    environment:
      MYSQL_HOST: mysqldatabase
      MYSQL_DATABASE: netguru
    depends_on:
      - mysqldatabase
    stdin_open: true
    tty: true
    ports:
      - published: ${APP_PORT:-3000}
        target: 3000
    entrypoint: ["wait-for-it.sh", "-s", "-t", "60", "mysqldatabase:3306", "--"]
    command: ["node", "./lib/main.js"]

volumes:
  db-config:
  db-data:
